stages:
  data_ingestion:
    cmd: python data_ingestion.py
    deps:
      - data/raw/data.csv
      - src/data_ingestion.py
    outs:
      - data/raw

  data_preprocessing:
    cmd: python data_preprocessing.py
    deps:
      - data/raw
      - src/data_preprocessing.py
    outs:
      - data/processed

  feature_engineering:
    cmd: python feature_engineering.py
    deps:
      - data/processed/
      - src/feature_engineering.py
    outs:
      - data/features

  model_building:
    cmd: python model_building.py
    deps:
      - data/features/
      - src/model_building.py
    outs:
      - model.pkl

  model_evaluation:
    cmd: python model_evaluation.py
    deps:
      - data/features/
      - model.pkl
    outs:
      - metrics.json

  prediction:
    cmd: python prediction.py
    deps:
      - model.pkl
      - data/features/
    outs:
      - predictions.csv

  user_interface:
    cmd: python user_interface.py --model model.pkl --data data/features/
    deps:
      - model.pkl
      - data/features/
    outs:
      - user_interface.html 

  deployment:
    cmd: python deployment.py
    deps:
      - user_interface.html
    outs:
      - deployment.html


      Provisional Registration Number: 118604933
Password: eNffhpZ7